### ISSUE TITLE
FUNCTION_INVOCATION_TIMEOUT error when using the API

### ISSUE THREAD

**Issue by reykim7854** [nerufars/rest-api-blue-archive#10]
Hello, I wanted to try using the REST API that you created, but it seems that it can't return the requested data. Here's the payload that I've got in postman.

![image](https://user-images.githubusercontent.com/42672058/188275775-a35b3553-7f0a-42ba-b11c-c9d199c67f87.png)

do you know what the problem is? or am I missing something?

**Comment by nerufars** [comment]
Hello to, Sorry i seem to have deploy error, but i will fix the problem

**Comment by nerufars** [comment]
Use this url  https://api-blue-archive.netlify.app
